kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: argocd-route
  namespace: argocd
  labels:
    app.kubernetes.io/instance: argocd
spec:
  to:
    kind: Service
    name: argocd-server
    weight: 100
  port:
    targetPort: https
  tls:
    termination: passthrough
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
